# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
snapcrafts:
  -
    publish: true
    summary: obt is a downloader for the GitHub release page.
    description: obt is a downloader for the GitHub release page.
    confinement: classic
    license: MIT
    base: core18
    apps:
      drumroll:
        plugs: ["network", "personal-files"]
    plugs:
      personal-files:
        read:
        - $HOME/.config/obt/config.toml
        write:
        - $HOME/.config/obt/config.toml
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
