[default]
dependencies = ["build"]

[test]
command = ["go", "test", "-v", "./..."]

[clean]
command = ["go", "clean", "-testcache"]

[build]
command = ["go", "build"]
dependencies = ["tidy", "clean"]

[lint]
dependencies = ["golangci-lint"]

[golangci-lint]
command = ["golangci-lint", "run", "-D", "errcheck", "./..."]

[tidy]
command = ["go", "mod", "tidy"]
