[default]
dependencies = ["build"]

[test]
command = ["go", "test", "-v", "./..."]

[clean]
command = ["go", "clean", "-testcache"]

[build]
command = ["go", "build"]
dependencies = ["tidy", "clean"]

[lint]
dependencies = ["staticcheck"]

[staticcheck]
command = ["staticcheck", "./..."]

[install_tools]
command = ["go", "-u", "golang.org/x/lint/golint", "honnef.co/go/tools/cmd/staticcheck"]

[tidy]
command = ["go", "mod", "tidy"]
