name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.23"]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download
      env:
        GO111MODULE: on

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: -D errcheck

    - name: govulncheckg
      uses: golang/govulncheck-action@v1

    - name: Run test
      run: |
        go test -v ./...
      env:
        GO111MODULE: on
